services:
  ark-server:
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8192M
    environment:
      ADMIN_PASSWORD: arkadminpass
      BETA: preaquatica
      MAX_PLAYERS: '20'
      NVIDIA_VISIBLE_DEVICES: void
      RCON_PORT: '27020'
      SERVER_MAP: Ragnarok
      SERVER_PASSWORD: ''
      SESSION_NAME: Clan 10x (Rag)
      TZ: America/Chicago
      UPDATE_ON_START: 'true'
    group_add:
      - 568
    image: hermsi/ark-server:latest
    platform: linux/amd64
    ports:
      - mode: ingress
        protocol: udp
        published: 27015
        target: 27015
      - mode: ingress
        protocol: tcp
        published: 27020
        target: 27020
      - mode: ingress
        protocol: udp
        published: 7777
        target: 7777
      - mode: ingress
        protocol: udp
        published: 7778
        target: 7778
    privileged: True
    pull_policy: missing
    restart: unless-stopped
    stdin_open: False
    tty: False
    volumes:
      - bind:
          create_host_path: True
          propagation: rprivate
        read_only: False
        source: /mnt/Primary/configuration/ark-server/Ragnarok
        target: /app
        type: bind
version: 1.0.0
x-action-required: False
x-notes: >
  # iX App This code was cloned from ```hit ``` and updated/modified to run
  easier as a Custom TrueNAS app.

  # Starting the Server:
  1) Run this command in your shell ```zfs set aclmode=passthrough Primary/configuration/ark-server/Ragnarok``` Note this path is the Dataset setup in TrueNAS.
  Simply copy the contents of docker-compose.true-nas-yml
  into the custom yml section for creating new apps in TrueNAS.

  ## Bug Reports and Feature Requests If you find a bug in this app or have an
  idea for a new feature, please try to fix it or file an issue at

  https://github.com/truenas/apps
x-portals: []